CREATE TABLE IF NOT EXISTS empleados(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    edad INT NOT NULL,
    sexo VARCHAR(255) NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    salario BIGINT NOT NULL
);